### ISSUE TITLE
Unable to install and run

### ISSUE THREAD

**Issue by Coder2012** [net-uk-sweet/whos-getting-the-brews#1]
After doing npm install and bower install, then running grunt, I get the following error:

Can't find config file: .jshintrc

**Comment by net-uk-sweet** [comment]
Thanks for pointing that out Coder2012 - I'd lazily opted for a full Yeoman scaffolding just for the server and live reload stuff, so running the default grunt task was attempting to do a bunch of stuff I don't need and which consequently wasn't configured properly. I've now trimmed down the Gruntfile to include only the server task and set that as the default. I've also removed all the unnecessary dependencies from package.json. Please let me know if that fixes it for you.

**Comment by Coder2012** [comment]
Fixed - closing
